# Nginxの公式image
FROM nginx:1.27.0

# nodeとnpmのinstall
# RUN apt install -y nodejs npm
# RUN apk add --no-cache bash

COPY wait.sh /wait.sh

RUN chmod +x /wait.sh

CMD ["/wait.sh", "web_front:3000", "--", "nginx", "-g", "daemon off;"]






RUN rm /etc/nginx/conf.d/default.conf
COPY default.nginx_front.conf /etc/nginx/conf.d
