version: "3.7"

services:
  web_app:
    container_name: web_app
    env_file: ./backend/web_app/.env
    build:
      context: ./backend/web_app/.
      dockerfile: Dockerfile.web_app
    volumes:
      - ./backend/web_app:/code/
      - static_volume:/code/staticfiles # <-- bind the static volume
    stdin_open: true
    tty: true
    networks:
      - backend_network
    command: gunicorn --bind :8000 config.wsgi:application
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    #   - DJANGO_SETTINGS_MODULE=config.local_settings
    # depends_on:
    #   - db

  nginx:
    container_name: nginx
    build:
      context: ./backend/nginx/.
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    networks:
      - backend_network
    tty: true



# test


networks:
  backend_network:
    driver: bridge
volumes:
  static_volume:
