# Generated by Django 5.0.6 on 2024-07-20 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procmanual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procmanual',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='procmanual',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
