# Generated by Django 5.0.6 on 2024-07-21 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procmanual', '0002_procmanual_created_date_procmanual_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procmanual',
            name='body',
        ),
    ]
