# Generated by Django 5.0.6 on 2024-07-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procmanual', '0003_remove_procmanual_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='procmanual',
            name='check_cmd',
            field=models.JSONField(default=list),
        ),
    ]
