# Generated by Django 5.0.6 on 2024-07-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procmanual', '0004_procmanual_check_cmd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procmanual',
            name='check_cmd',
        ),
    ]
