# Generated by Django 5.0.6 on 2024-07-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procmanual', '0005_remove_procmanual_check_cmd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procmanual',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
