# Generated by Django 5.0.6 on 2024-07-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procmanual', '0006_alter_procmanual_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procmanual',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
