# Generated by Django 5.0.6 on 2024-07-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procmanual', '0007_alter_procmanual_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='procmanual',
            name='check_cmd',
            field=models.JSONField(default=list),
        ),
    ]
