# Generated by Django 5.0.6 on 2024-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procmanual', '0008_procmanual_check_cmd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procmanual',
            name='check_cmd',
            field=models.JSONField(),
        ),
    ]
