# Generated by Django 5.0.6 on 2024-07-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procmanual', '0010_alter_procmanual_check_cmd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procmanual',
            name='check_cmd',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
