# Generated by Django 5.0.6 on 2024-07-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procmanual', '0011_alter_procmanual_check_cmd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procmanual',
            name='check_cmd',
        ),
    ]
