# Generated by Django 5.0.6 on 2024-07-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procmanual', '0013_procmanual_check_cmd_procmanual_check_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procmanual',
            name='check_cmd',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='procmanual',
            name='check_list',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='procmanual',
            name='execute_cmd',
            field=models.JSONField(blank=True),
        ),
    ]
