# Generated by Django 5.0.6 on 2024-07-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procmanual', '0015_alter_procmanual_check_cmd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procmanual',
            name='check_cmd',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='procmanual',
            name='check_list',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='procmanual',
            name='execute_cmd',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
