# python:3.12.4の公式 image をベースの image として設定
FROM python:3.12.4

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set work directory
WORKDIR /code

# install dependencies
COPY requirements.txt ./
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt



# Gunicornの実行
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]

# Copy project
COPY . ./

# Expose application port
EXPOSE 8000

